### ISSUE TITLE
Different ZIM file is getting created 

### ISSUE THREAD

**Issue by Sudarshan-21** [openzim/kolibri#116] opened 2024-03-27 18:13 UTC
**Description:**
When I run `docker run -v my_dir:/output ghcr.io/openzim/kolibri kolibri2zim --channel-id 7f744ce8d28b471eaf663abd60c92267 --name testchannel`  the following ZIM is created
![Screenshot from 2024-03-27 23-17-29](https://github.com/openzim/kolibri/assets/137636943/cb349acd-f56c-4f47-a904-b3773cfa7359)

and when i created a Docker image with the code in the new_ui branch using `docker build -t myimg .` and then i created ZIM file using `docker run -v my_dir:/output myimg kolibri2zim --channel-id 7f744ce8d28b471eaf663abd60c92267 --name testchannelmyimgbuild` the following ZIM is created
![Screenshot from 2024-03-27 23-17-53](https://github.com/openzim/kolibri/assets/137636943/03d97a48-68e2-4f7d-b160-8e0ce3036f40)

I assume that these two zim files should be same because i havent made any chanes to the code. Please correct me if I am wrong.

**Comment by benoit74** [comment] 2024-03-27 18:38
These ZIMs are different because it is the whole purpose of the `new_ui` branch: create a new UI for the ZIM. The branch is not yet merged into `main` because it has some "regressions / limitations" to fix first: see the https://github.com/openzim/kolibri/milestone/4 milestone

**Closed** 2024-03-27 18:38 UTC

**Comment by benoit74** [comment] 2024-03-27 18:45
Edit: everything is now in https://github.com/openzim/kolibri/milestone/8 milestone, I don't know why there was two milestones for the new UI
